name: Corregir contacto de rutinas

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/corregir-contacto-rutinas.yml'

permissions:
  contents: write

jobs:
  corregir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Corregir enlace dinámico de contacto
        run: |
          sed -i 's#https://gabriel-lsp.github.io/accesos-complementarios/contacto.html#https://crebe-ucayali.github.io/accesos-complementarios/paginas/contacto.html#g' rutinas/rutinas.js
          git rm .github/workflows/corregir-contacto-rutinas.yml
      - name: Guardar cambios
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Corregir enlace de contacto en rutinas'
          git push
